### ISSUE TITLE
Snippet in README correct?

### ISSUE THREAD

**Issue by Moredread** [noctux/philote#1]
Hi,

shouldn't it be **name** instead of **pkg** in the README for the dependency installation snippet?

**Comment by noctux** [comment]
Hey,

Are we talking about this part?

```yaml
      - name: Installing dependencies for file-related modules
        opkg: pkg=luaposix,coreutils-sha1sum state=present update_cache=yes
```

I've got to admit that the use of "pkg" is not very ideomatic here, as I'm making use of an (undocumented, as fas as I know) alias. The alias is defined [here](https://github.com/noctux/philote/blob/5023d9c4da048b505f6448b2e679f5b8552fe02b/src/opkg.lua#L94).
It mirrors the alias present in ansible's [upstream opkg module](https://github.com/ansible/ansible/blob/0b8011436dc7f842b78298848e298f2a57ee8d78/lib/ansible/modules/packaging/os/opkg.py#L164).

Hope this clarifies things :)
But maybe I should change that section. It was merely copied from my personal router config without too much consideration...

**Comment by Moredread** [comment]
Oh, that makes sense.

I had problems getting that line to work, and after I rewrote it (using name) it worked, so I thought it was an issue with that. But it was just that the indentation was wrong after I pasted your snippet, i.e. it works fine now.

**Comment by noctux** [comment]
Glad to hear, closing this then for now :)

Feel free to notify me when other issues arise.
